### ISSUE TITLE
Create GH action that renders README.md from README.Rmd

### ISSUE THREAD

**Issue by ErdaradunGaztea** [KotulskaLab/AmyloGraph#107]

**Comment by DominikRafacz** [comment]
This might be useful for this task, @ErdaradunGaztea :
https://fromthebottomoftheheap.net/2020/04/30/rendering-your-readme-with-github-actions/

**Comment by DominikRafacz** [comment]
And here is some more code:

https://github.com/marketplace/actions/github-action-for-rmarkdown
