### ISSUE TITLE
Multi-chain sequences

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#109]
Some of the proteins are multi-chain (e.g., insulin). How to effectively store both chains in the database considering that we would love to still work with the flat tables?

**Comment by michbur** [comment]
Right now we store this as follows:
>chainA
XYZ
>chainB 
ZYX

**Comment by ErdaradunGaztea** [comment]
- [ ] interpret text as names and sequences
- [ ] restructure in-memory data storage to allow lists of sequences, not only single sequences
- [ ] implement printing multiple sequences in Interaction Details

**Comment by ErdaradunGaztea** [comment]
Works just fine in my opinion (temporary example here of course):

![image](https://user-images.githubusercontent.com/32573962/159247668-83b9aed5-e607-4516-ac7e-b8efc696678b.png)

**Comment by michbur** [comment]
How the filtering (filter by motif) works on multi-chain sequences? Make sure that filtering returns sequences that have the motif in at least one chain.
