### ISSUE TITLE
Display chain sequences in rows of 80 bp

### ISSUE THREAD

**Issue by ErdaradunGaztea** [KotulskaLab/AmyloGraph#114]
Some sequences are a few hundred long and the user has to scroll right to read it all. If it was split in rows of 80 bp (as many FASTA files are), it would be much more readable.

**Comment by michbur** [comment]
Cool idea, but how about setting the default value to 80 amino acids and providing the user with a way to customize it?

**Comment by ErdaradunGaztea** [comment]
An example of a very long sequence:

![image](https://user-images.githubusercontent.com/32573962/176898297-67051a33-054b-424d-8af2-ec11f178ce54.png)
