### ISSUE TITLE
Change app startup method

### ISSUE THREAD

**Issue by ErdaradunGaztea** [KotulskaLab/AmyloGraph#137]
Get rid of `app.R` in `inst` folder. This requires rewriting paths, so probably create an `ag_file(...)` function that passes to `system.file(..., package = "AmyloGraph")` or something like that.

**Comment by michbur** [comment]
I dont think that AmyloGraph's server logic allows us to run AmyloGram at escience without app.R.

**Comment by ErdaradunGaztea** [comment]
I've dabbled with that a little and I believe it could be done... but I don't think it's worth the required time investment. Too little to gain for this much work.
