### ISSUE TITLE
Right panel

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#14]
- [x] limited tables: only interactor/interactee and DOI
  - [x] add amylograph ID to the tables (#15)
- [x] (possibly) panel auto-resizing upon selecting/deselecting a node
- [x] #17
- [x] selection of records moves the user to the main table with these record selected

**Comment by DominikRafacz** [comment]
Almost implemented on branch `feature/show-in-table`. There are few things to implement yet:

* [ ] Reimplement select and deselect all buttons for subtables
* [ ] Disallow moving selection when not applying filters in the right panel
* [ ] Rethink columns of tables
* [ ] Rearrange buttons

I'll probably do it all tomorrow

**Comment by DominikRafacz** [comment]
* [ ] Make sure table is rendered before showing selection in it

**Comment by DominikRafacz** [comment]
Select and deselect all buttons impplemented in 3d90386c5ae5d206a917341430eb0791a686290d .

**Comment by DominikRafacz** [comment]
The last of the original tasks is closed with #67 .
Closing this issue and moving other tasks to other issues.
