### ISSUE TITLE
Download tab

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#140]
Add a download tab, where there is 
 - a link to the download of the main source table: https://raw.githubusercontent.com/KotulskaLab/AmyloGraph/main/inst/AmyloGraph/interactions_data.csv
 - a link do to package on github

**Comment by ErdaradunGaztea** [comment]
Sounds like a bad idea to me, since we have a lot of download buttons here and there -- below the graph, over the main table. A tab would look like all download buttons reside there and that would be misleading. Perhaps a section in "About" tab?

**Comment by michbur** [comment]
Understood, @michbur add the info in the about section.
