### ISSUE TITLE
Increase the size of tabPabel buttons

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#148]
TabPanel buttons (about, graph, table) are too small and too obscure. Is there any way to make them more distinctive?

**Comment by ErdaradunGaztea** [comment]
Would this be big enough?

![image](https://user-images.githubusercontent.com/32573962/181010453-04625b12-2a17-4849-9872-bdad12564e6b.png)
![image](https://user-images.githubusercontent.com/32573962/181010508-c397a678-1b16-4986-a305-cf998e52416d.png)

**Comment by michbur** [comment]
Is it possible to also possible to make buttons a little more erhm, buttony?

**Comment by ErdaradunGaztea** [comment]
What do you mean? Do you mean that these tabs should have a background a bit different to the background of the panel? Or something else?

**Comment by michbur** [comment]
haha, I knew that 'buttony' isn't a good word. Make them a little bit more distinct, like slightly shaded.

https://res.cloudinary.com/practicaldev/image/fetch/s--poIDWkjF--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/i/uckrx1egkxfmdzqavmyq.png

**Comment by ErdaradunGaztea** [comment]
Is this a progress in the right direction?

![image](https://user-images.githubusercontent.com/32573962/181058848-b5bfb48d-005e-4bb6-a341-119a4d485e02.png)

**Comment by michbur** [comment]
It's perfect!
