### ISSUE TITLE
Missing edges after "group by"

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#151]
After grouping edges, deselecting all edges in the group and changing "group edges" to none, the graph is not reset to the previous state. Instead, all edges all still missing.
![Zrzut ekranu z 2022-08-02 20-00-08](https://user-images.githubusercontent.com/5267317/182443206-9bf12621-3c41-41cb-ad6e-bffae1427269.png)

**Comment by ErdaradunGaztea** [comment]
I fail to see a problem. It is intended to work this way -- that you can group and ungroup edges with the current filter settings.

**Comment by michbur** [comment]
Let's talk about this tomorrow.

**Comment by michbur** [comment]
How blind and stupid I am!
