### ISSUE TITLE
Rendering images in readme

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#153]
markdown_images() (https://github.com/KotulskaLab/AmyloGraph/blob/main/R/markdown_texts.R#L106) is problematic for pkgdown because "pkgdown can only use images in 'man/figures' and 'vignettes' " (see also https://github.com/KotulskaLab/AmyloGraph/runs/7715567472?check_suite_focus=true#step:6:207)

**Comment by ErdaradunGaztea** [comment]
There's no reason for them to be in `inst` folder, we can move them, I suppose.

**Comment by michbur** [comment]
So lets move them to vignette

**Comment by michbur** [comment]
Still the same issue: https://github.com/KotulskaLab/AmyloGraph/runs/7754492693?check_suite_focus=true#step:6:207

**Comment by ErdaradunGaztea** [comment]
I know, that's why I reopened it.

**Comment by michbur** [comment]
Fixed, paths were wrong.
