### ISSUE TITLE
Bug in group edges

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#23]
Group edges after selecting a filter leave some edges visible

![Example of this behavior](https://user-images.githubusercontent.com/5267317/131905378-269f6f77-e164-4b3b-94f3-72580cb65179.png)

**Comment by ErdaradunGaztea** [comment]
Do you remember the steps you made so that I could reproduce it? As far as I remember, it only happens after launching the app the first time after building the package.

**Comment by michbur** [comment]
I was using the newest version of the app hosted on linode. I opened the app, selected the filter node info and was deselecting filter by interactee aggregation speed.
