### ISSUE TITLE
Buggy table on smaller screens

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#24]
![Zrzut ekranu z 2021-09-07 15-28-21](https://user-images.githubusercontent.com/5267317/132353019-d7838bf6-ff99-43e8-8c57-52c23094a970.png)

On smaller screens, the DOI search box can be unreachable. I can easily scroll the table via slider, but cannot scroll the search bar with column names.

**Comment by ErdaradunGaztea** [comment]
Perhaps a possible workaround would be as described [here](https://datatables.net/forums/discussion/comment/128441/#Comment_128441), precisely the following part:

> Having said that, if you do want the horizontal scrollbar below the table, remove the `scrollX` option and place a `div` wrapper around the table which have `overflow-x: auto` so that the whole table will scroll.
