### ISSUE TITLE
Sequence view in the interaction panel

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#30]
The sequence view should contain the UniProt-like numbering, for example:
![Zrzut ekranu z 2021-09-09 14-47-20](https://user-images.githubusercontent.com/5267317/132688438-66fd6743-2531-491a-85fe-8db2dea87e2d.png)

**Comment by ErdaradunGaztea** [comment]
Should these be split into multiple lines or simply having numbers in the first line and sequence in the second would suffice?
