### ISSUE TITLE
NA in filter options

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#31]
The newest version of AmyloGram contains NA in filters (Filter by "interactee aggregation speed" and Filter by "heterogenous fibers")
![Zrzut ekranu z 2021-09-16 08-19-11](https://user-images.githubusercontent.com/5267317/133560050-64f6169a-6008-4ffc-89e2-14c26f2320c8.png)

**Comment by DominikRafacz** [comment]
That's the result of presence of NA in source data. File `AmyloGraph.RDS` contain NA values in column `Is the interactor affecting interactee’s aggregating speed` in record number 570 and in column `Is interaction resulting in heterogeneous fibrils consisting of interactor and interactee molecules?` in records number 232, 233, 236, 239 (those numbers are also AGIDs of those interactions). @michbur, would you update the data and find out why those NAs are present in the first place? I assume we still have no access to the source.

**Comment by michbur** [comment]
I will fix this tomorrow. It stems from bad practice of revising curated data.
