### ISSUE TITLE
Add exports to graph formats

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#44]
EDIT: Laura hijacked this comment to have a task list displayed in the issue

Formats:
- [ ] CX - possible with [Github-hosted RCX package](https://github.com/frankkramer-lab/RCX)
- [ ] cyjs
- [ ] graphML - possible with `igraph::write_graph()`
- [ ] NNF
- [x] xGMML

Won't do:
- [x] SIF - possible with [this gist](https://gist.github.com/wjrl/f382598751d44397219ea037dd7a6581)
unsuitable for networks with attributes

**Comment by michbur** [comment]
[RCy3::exportNetwork](https://github.com/cytoscape/RCy3/) covers: SIF,, CX, cyjs, graphML, NNF, xGMM

**Comment by ErdaradunGaztea** [comment]
Other formats I encountered:
- [ ] gexf - possible with [this code](https://gk.palem.in/iGraphExport.html#GexfExport)

**Comment by ErdaradunGaztea** [comment]
Removed from milestone since at least one export format is implemented now.

**Comment by michbur** [comment]
We will re-open this issue if we need more export formats. Right now we are fine. Great work @ErdaradunGaztea
