### ISSUE TITLE
Advanced sequence processing

### ISSUE THREAD

**Issue by michbur** [KotulskaLab/AmyloGraph#88]
The filed sequence in the source data can have two values: amino acid sequence or a following string 'sequence unavailable (protein complex)'. This 'sequence unavailable (protein complex)' can be treated as NA. However, the NA makes the view of the interaction more complicated as we cannot provide any sequences there.

Also, Michał is bad at planning the data structure.

**Comment by michbur** [comment]
Let's do that. In next iterations, we will use NA.

**Comment by DominikRafacz** [comment]
Closed by 73a4435308fc321a8962c3a5ea2dbea5754b1bfb
